#!/usr/bin/env python

import logging

from ml_training_template.components.logger import setup_logging
from ml_training_template.experiment.artifacts import ExperimentArtifacts
from ml_training_template.experiment.experiment import Experiment
from ml_training_template.experiment.model import ProjectModel
from ml_training_template.utils.arg_parser import TrainArgParser

setup_logging()
logger = logging.getLogger()

if __name__ == '__main__':
    logger.info(f"Begin train.py")

    arg_parser = TrainArgParser()
    args = arg_parser.get_arguments()

    run_tag = f"{args.project_name}-{args.run_tag}"
    dataset_path = args.input_dir

    model = ProjectModel()

    artifacts_handler = ExperimentArtifacts(
        run_tag=run_tag,
        model_name=model.model_id,
        base_path=args.output_dir,
    )
    experiment = Experiment(
        model=model,
        input_dir=dataset_path,
        artifacts_handler=artifacts_handler,
    )
    experiment.run()

    logger.info(f"End train.py")
